from datetime import datetime, timedelta
from enum import Enum
import json
import logging
import os
from pathlib import Path
import time
from typing import Any, List
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode
from urllib.request import Request, urlopen

from fastapi import BackgroundTasks, Body, Depends, FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import RedirectResponse
from dotenv import load_dotenv
from pydantic import BaseModel, Field

from integrations.errors import ApiFailureError, ConnectorError, ConnectorErrorCode, serialize_connector_error
from integrations.models import ConnectionTestResult, IntegrationHealth, NormalizedQuestion
from integrations.registry import services as integration_services
from database import Base, SessionLocal, engine, get_db
from db_models import AiSuggestion, CompanySettings, Integration, ProductCache, QuestionRecord
from db_seed import DEFAULT_COMPANY_ID, DEFAULT_PROVIDER, seed_defaults
from sqlalchemy import Text, cast, or_, text
from sqlalchemy.orm import Session


load_dotenv()
logger = logging.getLogger(__name__)
ML_TOKEN_PATH = Path(__file__).with_name("mercadolivre_tokens.json")
ML_AUTH_BASE_URL = "https://auth.mercadolivre.com.br/authorization"
ML_API_BASE_URL = "https://api.mercadolibre.com"
DATABASE_READY = False


def init_database() -> None:
    global DATABASE_READY
    try:
        Base.metadata.create_all(bind=engine)
        ensure_database_columns()
        db = SessionLocal()
        try:
            seed_defaults(db)
            integration = get_ml_integration(db)
            if not integration.access_token and ML_TOKEN_PATH.exists():
                try:
                    legacy_tokens = json.loads(ML_TOKEN_PATH.read_text(encoding="utf-8"))
                except json.JSONDecodeError:
                    legacy_tokens = {}
                if legacy_tokens.get("access_token"):
                    integration.access_token = legacy_tokens.get("access_token")
                    integration.refresh_token = legacy_tokens.get("refresh_token")
                    integration.seller_id = str(legacy_tokens.get("seller_id") or legacy_tokens.get("user_id") or "")
                    expires_at = legacy_tokens.get("expires_at")
                    integration.expires_at = (
                        datetime.fromtimestamp(int(expires_at)) if expires_at else None
                    )
                    integration.token_status = "valid"
                    integration.last_sync = datetime.utcnow()
                    integration.updated_at = datetime.utcnow()
                    db.commit()
        finally:
            db.close()
        DATABASE_READY = True
    except Exception:
        DATABASE_READY = False
        logger.exception("Database initialization failed. API will keep running with frontend/demo fallbacks.")


def ensure_database_columns() -> None:
    ai_suggestion_columns = {
        "suggestion_text": "TEXT",
        "edited_text": "TEXT",
        "final_answer": "TEXT",
    }
    integration_columns = {
        "expires_in": "INTEGER",
    }
    product_cache_columns = {
        "id": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "company_id": "VARCHAR(64) NOT NULL",
        "provider": "VARCHAR(80) NOT NULL",
        "external_id": "VARCHAR(120) NOT NULL",
        "title": "TEXT NOT NULL DEFAULT ''",
        "permalink": "TEXT",
        "price": "VARCHAR(80)",
        "currency_id": "VARCHAR(20)",
        "status": "VARCHAR(80)",
        "available_quantity": "INTEGER",
        "thumbnail": "TEXT",
        "category_id": "VARCHAR(120)",
        "listing_type_id": "VARCHAR(120)",
        "condition": "VARCHAR(80)",
        "seller_custom_field": "TEXT",
        "attributes_json": "JSONB NOT NULL DEFAULT '[]'::jsonb",
        "variations_json": "JSONB NOT NULL DEFAULT '[]'::jsonb",
        "raw_payload": "JSONB NOT NULL DEFAULT '{}'::jsonb",
        "last_synced_at": "TIMESTAMP",
        "created_at": "TIMESTAMP NOT NULL DEFAULT NOW()",
        "updated_at": "TIMESTAMP NOT NULL DEFAULT NOW()",
    }
    with engine.begin() as connection:
        if engine.dialect.name == "postgresql":
            for column, column_type in ai_suggestion_columns.items():
                connection.execute(
                    text(f"ALTER TABLE ai_suggestions ADD COLUMN IF NOT EXISTS {column} {column_type}")
                )
            for column, column_type in integration_columns.items():
                connection.execute(
                    text(f"ALTER TABLE integrations ADD COLUMN IF NOT EXISTS {column} {column_type}")
                )
            connection.execute(
                text(
                    "CREATE TABLE IF NOT EXISTS products_cache ("
                    + ", ".join(f"{column} {column_type}" for column, column_type in product_cache_columns.items())
                    + ")"
                )
            )
            connection.execute(
                text(
                    "CREATE UNIQUE INDEX IF NOT EXISTS uq_product_cache_external "
                    "ON products_cache (company_id, provider, external_id)"
                )
            )
        elif engine.dialect.name == "sqlite":
            existing = {
                row[1]
                for row in connection.execute(text("PRAGMA table_info(ai_suggestions)")).fetchall()
            }
            for column, column_type in ai_suggestion_columns.items():
                if column not in existing:
                    connection.execute(text(f"ALTER TABLE ai_suggestions ADD COLUMN {column} {column_type}"))
            existing_integrations = {
                row[1]
                for row in connection.execute(text("PRAGMA table_info(integrations)")).fetchall()
            }
            for column, column_type in integration_columns.items():
                if column not in existing_integrations:
                    connection.execute(text(f"ALTER TABLE integrations ADD COLUMN {column} {column_type}"))
            connection.execute(
                text(
                    "CREATE TABLE IF NOT EXISTS products_cache ("
                    "id INTEGER PRIMARY KEY AUTOINCREMENT, "
                    "company_id VARCHAR(64) NOT NULL, "
                    "provider VARCHAR(80) NOT NULL, "
                    "external_id VARCHAR(120) NOT NULL, "
                    "title TEXT NOT NULL DEFAULT '', "
                    "permalink TEXT, "
                    "price VARCHAR(80), "
                    "currency_id VARCHAR(20), "
                    "status VARCHAR(80), "
                    "available_quantity INTEGER, "
                    "thumbnail TEXT, "
                    "category_id VARCHAR(120), "
                    "listing_type_id VARCHAR(120), "
                    "condition VARCHAR(80), "
                    "seller_custom_field TEXT, "
                    "attributes_json JSON NOT NULL DEFAULT '[]', "
                    "variations_json JSON NOT NULL DEFAULT '[]', "
                    "raw_payload JSON NOT NULL DEFAULT '{}', "
                    "last_synced_at TIMESTAMP, "
                    "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                    "updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)"
                )
            )
            connection.execute(
                text(
                    "CREATE UNIQUE INDEX IF NOT EXISTS uq_product_cache_external "
                    "ON products_cache (company_id, provider, external_id)"
                )
            )


def normalize_db_status(status: str | None) -> str:
    normalized = (status or "").strip().lower()
    if normalized in {"respondida", "respondido", "answered", "responded", "closed"}:
        return "responded"
    return "pending"


def status_to_ui(status: str | None) -> str:
    return "Respondida" if normalize_db_status(status) == "responded" else "Pendente"


def get_suggestion_text(suggestion: AiSuggestion | None) -> str:
    if not suggestion:
        return ""
    return (
        suggestion.suggestion_text
        or suggestion.final_answer
        or suggestion.final_response
        or suggestion.original_suggestion
        or ""
    )


def get_final_answer(suggestion: AiSuggestion | None) -> str:
    if not suggestion:
        return ""
    return suggestion.final_answer or suggestion.final_response or suggestion.edited_text or ""


def parse_datetime(value: Any) -> datetime | None:
    if not value:
        return None
    if isinstance(value, datetime):
        return value
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).replace(tzinfo=None)
    except ValueError:
        return None


def get_default_settings(db: Session) -> CompanySettings:
    settings = (
        db.query(CompanySettings)
        .filter(CompanySettings.company_id == DEFAULT_COMPANY_ID)
        .first()
    )
    if settings:
        return settings
    seed_defaults(db)
    return (
        db.query(CompanySettings)
        .filter(CompanySettings.company_id == DEFAULT_COMPANY_ID)
        .one()
    )


def get_ml_integration(db: Session) -> Integration:
    integration = (
        db.query(Integration)
        .filter(
            Integration.company_id == DEFAULT_COMPANY_ID,
            Integration.provider == DEFAULT_PROVIDER,
        )
        .first()
    )
    if integration:
        return integration
    seed_defaults(db)
    return (
        db.query(Integration)
        .filter(
            Integration.company_id == DEFAULT_COMPANY_ID,
            Integration.provider == DEFAULT_PROVIDER,
        )
        .one()
    )


def question_to_api(question: QuestionRecord, db: Session | None = None) -> dict[str, Any]:
    suggestion = question.ai_suggestion
    suggestion_text = get_suggestion_text(suggestion)
    if not suggestion_text:
        suggestion_text = "Sugestão ainda não gerada. Clique em gerar nova sugestão."
    final_answer = get_final_answer(suggestion)
    related_products = search_related_products(
        f"{question.product_title or ''} {question.question_text or ''}",
        limit=3,
        db=db,
    ) if db else []
    return {
        "id": question.id,
        "company_id": question.company_id,
        "marketplace": "Mercado Livre" if question.provider == DEFAULT_PROVIDER else question.provider,
        "provider": question.provider,
        "external_id": question.external_id,
        "product": question.product_title,
        "product_title": question.product_title,
        "customer_name": "Cliente Mercado Livre",
        "question": question.question_text,
        "question_text": question.question_text,
        "created_at": (question.created_at or question.created_in_app_at).isoformat(),
        "status": status_to_ui(question.status),
        "db_status": normalize_db_status(question.status),
        "priority": "Media",
        "ai_suggestion": suggestion_text,
        "suggestion_text": suggestion.suggestion_text if suggestion else "",
        "edited_text": suggestion.edited_text if suggestion else "",
        "final_answer": final_answer,
        "final_response": final_answer,
        "has_ai_suggestion": bool(get_suggestion_text(suggestion)),
        "was_edited": suggestion.was_edited if suggestion else False,
        "instruction_used": suggestion.instruction_used if suggestion else "",
        "answered_at": question.answered_at.isoformat() if question.answered_at else None,
        "approved_by": suggestion.approved_by if suggestion else None,
        "approved_at": suggestion.approved_at.isoformat() if suggestion and suggestion.approved_at else None,
        "sku": (question.raw_payload or {}).get("item_id") or "ML",
        "price": "",
        "raw_payload": question.raw_payload or {},
        "related_products": related_products,
        "is_real": True,
        "channel": "mercado_livre",
    }


def get_cors_origins() -> list[str]:
    raw_origins = os.getenv(
        "CORS_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173",
    )
    return [origin.strip() for origin in raw_origins.split(",") if origin.strip()]


def get_ml_config() -> dict[str, str]:
    return {
        "client_id": os.getenv("ML_CLIENT_ID") or os.getenv("MERCADO_LIVRE_CLIENT_ID") or "",
        "client_secret": os.getenv("ML_CLIENT_SECRET") or os.getenv("MERCADO_LIVRE_CLIENT_SECRET") or "",
        "redirect_uri": os.getenv("ML_REDIRECT_URI") or os.getenv("MERCADO_LIVRE_REDIRECT_URI") or "",
    }


def ml_is_configured() -> bool:
    config = get_ml_config()
    return all(config.values())


def read_ml_tokens() -> dict[str, Any]:
    db = SessionLocal()
    try:
        integration = get_ml_integration(db)
        if not integration.access_token and not integration.refresh_token:
            return {}
        expires_at = int(integration.expires_at.timestamp()) if integration.expires_at else 0
        return {
            "access_token": integration.access_token,
            "refresh_token": integration.refresh_token,
            "seller_id": integration.seller_id,
            "user_id": integration.seller_id,
            "expires_in": integration.expires_in,
            "expires_at": expires_at,
            "token_status": integration.token_status,
            "connected_at": integration.created_at.isoformat() if integration.created_at else None,
            "updated_at": integration.updated_at.isoformat() if integration.updated_at else None,
        }
    finally:
        db.close()


def save_ml_tokens(token_data: dict[str, Any]) -> dict[str, Any]:
    expires_in = int(token_data.get("expires_in") or 0)
    expires_at = datetime.utcnow() + timedelta(seconds=expires_in)
    db = SessionLocal()
    try:
        integration = get_ml_integration(db)
        integration.access_token = token_data.get("access_token")
        integration.refresh_token = token_data.get("refresh_token") or integration.refresh_token
        integration.seller_id = str(token_data.get("user_id") or token_data.get("seller_id") or integration.seller_id or "")
        integration.expires_in = expires_in
        integration.expires_at = expires_at
        integration.token_status = "valid"
        integration.last_sync = datetime.utcnow()
        integration.updated_at = datetime.utcnow()
        db.commit()
        token_data["expires_at"] = int(expires_at.timestamp())
        return token_data
    finally:
        db.close()


def update_ml_tokens(updates: dict[str, Any]) -> dict[str, Any]:
    db = SessionLocal()
    try:
        integration = get_ml_integration(db)
        if "access_token" in updates:
            integration.access_token = updates["access_token"]
        if "refresh_token" in updates:
            integration.refresh_token = updates["refresh_token"]
        if "seller_id" in updates or "user_id" in updates:
            integration.seller_id = str(updates.get("seller_id") or updates.get("user_id") or "")
        if "expires_in" in updates:
            integration.expires_in = int(updates["expires_in"])
        if "expires_at" in updates:
            integration.expires_at = datetime.fromtimestamp(int(updates["expires_at"]))
        integration.token_status = updates.get("token_status") or integration.token_status or "valid"
        integration.updated_at = datetime.utcnow()
        db.commit()
    finally:
        db.close()
    tokens = read_ml_tokens()
    tokens.update(updates)
    return tokens


def ml_connected_at(tokens: dict[str, Any]) -> datetime | None:
    raw_value = tokens.get("connected_at") or tokens.get("updated_at")
    if not raw_value:
        return None
    try:
        return datetime.fromisoformat(str(raw_value))
    except ValueError:
        return None


def format_optional_datetime(value: datetime | None) -> str | None:
    return value.isoformat() if value else None


def ml_request_json(url: str, *, method: str = "GET", data: dict[str, Any] | None = None, access_token: str | None = None) -> dict[str, Any]:
    body = None
    headers = {"Accept": "application/json"}
    if data is not None:
        body = urlencode(data).encode("utf-8")
        headers["Content-Type"] = "application/x-www-form-urlencoded"
    if access_token:
        headers["Authorization"] = f"Bearer {access_token}"

    request = Request(url, data=body, method=method, headers=headers)
    try:
        with urlopen(request, timeout=20) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as error:
        details = error.read().decode("utf-8", errors="replace")
        raise HTTPException(status_code=error.code, detail=f"Mercado Livre API error: {details}") from error
    except URLError as error:
        raise HTTPException(status_code=502, detail=f"Mercado Livre API unavailable: {error}") from error


def ml_request_json_with_status(
    url: str,
    *,
    method: str = "GET",
    json_data: dict[str, Any] | None = None,
    access_token: str | None = None,
) -> tuple[int, dict[str, Any]]:
    body = None
    headers = {"Accept": "application/json"}
    if json_data is not None:
        body = json.dumps(json_data, ensure_ascii=False).encode("utf-8")
        headers["Content-Type"] = "application/json; charset=utf-8"
    if access_token:
        headers["Authorization"] = f"Bearer {access_token}"

    request = Request(url, data=body, method=method, headers=headers)
    try:
        with urlopen(request, timeout=20) as response:
            response_text = response.read().decode("utf-8", errors="replace")
            response_body = json.loads(response_text) if response_text else {}
            return response.status, response_body
    except HTTPError as error:
        details = error.read().decode("utf-8", errors="replace")
        logger.error("Mercado Livre API error %s: %s", error.code, details)
        raise HTTPException(status_code=error.code, detail=f"Mercado Livre API error: {details}") from error
    except URLError as error:
        raise HTTPException(status_code=502, detail=f"Mercado Livre API unavailable: {error}") from error


def refresh_ml_token_if_needed(force: bool = False) -> dict[str, Any]:
    db = SessionLocal()
    try:
        access_token = get_valid_mercadolivre_token(db, force_refresh=force)
        integration = get_ml_integration(db)
        return {
            "access_token": access_token,
            "refresh_token": integration.refresh_token,
            "seller_id": integration.seller_id,
            "user_id": integration.seller_id,
            "expires_at": int(integration.expires_at.timestamp()) if integration.expires_at else 0,
            "token_status": integration.token_status,
        }
    finally:
        db.close()


def get_valid_mercadolivre_token(db: Session | None = None, *, force_refresh: bool = False) -> str:
    owns_session = db is None
    session = db or SessionLocal()
    try:
        integration = get_ml_integration(session)
        if not integration.access_token and not integration.refresh_token:
            logger.warning("Mercado Livre token unavailable: no access_token or refresh_token")
            raise HTTPException(status_code=401, detail="Mercado Livre não conectado.")

        refresh_threshold = datetime.utcnow() + timedelta(minutes=5)
        if (
            integration.access_token
            and integration.expires_at
            and integration.expires_at > refresh_threshold
            and not force_refresh
        ):
            logger.info("Mercado Livre token still valid until %s", integration.expires_at.isoformat())
            return integration.access_token

        if not integration.refresh_token:
            logger.warning("Mercado Livre token refresh failed: missing refresh_token")
            integration.token_status = "expired"
            integration.updated_at = datetime.utcnow()
            session.commit()
            raise HTTPException(status_code=401, detail="Mercado Livre refresh_token is missing")

        logger.info("Mercado Livre token refresh attempted")
        config = get_ml_config()
        try:
            refreshed = ml_request_json(
                f"{ML_API_BASE_URL}/oauth/token",
                method="POST",
                data={
                    "grant_type": "refresh_token",
                    "client_id": config["client_id"],
                    "client_secret": config["client_secret"],
                    "refresh_token": integration.refresh_token,
                },
            )
        except HTTPException:
            logger.exception("Mercado Livre token refresh failed")
            integration.token_status = "expired"
            integration.updated_at = datetime.utcnow()
            session.commit()
            raise

        expires_in = int(refreshed.get("expires_in") or integration.expires_in or 0)
        integration.access_token = refreshed.get("access_token") or integration.access_token
        integration.refresh_token = refreshed.get("refresh_token") or integration.refresh_token
        integration.expires_in = expires_in
        integration.expires_at = datetime.utcnow() + timedelta(seconds=expires_in)
        integration.seller_id = str(refreshed.get("user_id") or refreshed.get("seller_id") or integration.seller_id or "")
        integration.token_status = "valid"
        integration.updated_at = datetime.utcnow()
        session.commit()
        logger.info("Mercado Livre token refresh succeeded; expires_at=%s", integration.expires_at.isoformat())
        if not integration.access_token:
            raise HTTPException(status_code=401, detail="Mercado Livre token refresh did not return access_token")
        return integration.access_token
    finally:
        if owns_session:
            session.close()


def get_ml_seller_id(tokens: dict[str, Any]) -> str:
    seller_id = tokens.get("seller_id") or tokens.get("user_id")
    if seller_id:
        return str(seller_id)

    me = ml_request_json(f"{ML_API_BASE_URL}/users/me", access_token=tokens["access_token"])
    seller_id = me.get("id")
    if not seller_id:
        raise HTTPException(status_code=502, detail="Could not resolve Mercado Livre seller_id")
    update_ml_tokens({"seller_id": seller_id})
    return str(seller_id)


def normalize_ml_question_status(raw_status: str | None) -> str:
    status = (raw_status or "").lower()
    if status in {"unanswered", "pending", "opened", "active"}:
        return "Pendente"
    if status in {"answered", "closed"}:
        return "Respondida"
    return "Pendente"


def get_ml_product_title(item_id: str | None, access_token: str) -> str:
    if not item_id:
        return "Produto Mercado Livre"
    try:
        item = ml_request_json(f"{ML_API_BASE_URL}/items/{item_id}", access_token=access_token)
        return item.get("title") or item_id
    except HTTPException:
        return item_id


def normalize_ml_question(payload: dict[str, Any], access_token: str) -> dict[str, Any]:
    item_id = payload.get("item_id") or payload.get("item", {}).get("id")
    text = payload.get("text") or payload.get("question") or payload.get("body") or ""
    created_at = payload.get("date_created") or payload.get("created_at") or datetime.utcnow().isoformat()
    return {
        "channel": "mercado_livre",
        "external_id": str(payload.get("id") or payload.get("question_id") or ""),
        "product_title": get_ml_product_title(item_id, access_token),
        "question_text": text,
        "status": normalize_ml_question_status(payload.get("status")),
        "created_at": created_at,
        "raw_payload": payload,
    }


def upsert_ml_question(db: Session, normalized: dict[str, Any]) -> QuestionRecord:
    external_id = str(normalized.get("external_id") or "")
    if not external_id:
        raise HTTPException(status_code=502, detail="Mercado Livre question missing external_id")

    question = (
        db.query(QuestionRecord)
        .filter(
            QuestionRecord.company_id == DEFAULT_COMPANY_ID,
            QuestionRecord.provider == DEFAULT_PROVIDER,
            QuestionRecord.external_id == external_id,
        )
        .first()
    )
    if not question:
        question = QuestionRecord(
            company_id=DEFAULT_COMPANY_ID,
            provider=DEFAULT_PROVIDER,
            external_id=external_id,
        )
        db.add(question)

    question.product_title = normalized.get("product_title") or "Produto Mercado Livre"
    question.question_text = normalized.get("question_text") or ""
    question.status = normalize_db_status(normalized.get("status"))
    question.created_at = parse_datetime(normalized.get("created_at"))
    question.raw_payload = normalized.get("raw_payload") or {}
    question.updated_at = datetime.utcnow()
    return question


def ensure_initial_suggestion(db: Session, question: QuestionRecord) -> None:
    existing = question.ai_suggestion
    if existing and (existing.original_suggestion or existing.final_response):
        return
    settings = get_default_settings(db)
    related_products = search_related_products(
        f"{question.product_title or ''} {question.question_text or ''}",
        limit=5,
        db=db,
    )
    logger.info(
        "Injecting related products into initial AI suggestion external_id=%s count=%s",
        question.external_id,
        len(related_products),
    )
    try:
        suggestion_text = generate_openai_initial_suggestion(
            product_title=question.product_title,
            question_text=question.question_text,
            settings=settings,
            related_products=related_products,
        )
        logger.info("AI initial suggestion generated external_id=%s", question.external_id)
    except Exception as error:
        logger.exception("Failed to generate initial AI suggestion for question %s", question.external_id)
        suggestion_text = (
            "Não foi possível gerar a sugestão inicial da IA. "
            "Revise a pergunta e escreva uma resposta antes de enviar."
        )
    if existing:
        existing.original_suggestion = suggestion_text
        existing.suggestion_text = suggestion_text
        existing.final_response = suggestion_text
        existing.final_answer = suggestion_text
        existing.updated_at = datetime.utcnow()
    else:
        suggestion = AiSuggestion(
            question=question,
            original_suggestion=suggestion_text,
            suggestion_text=suggestion_text,
            final_response=suggestion_text,
            final_answer=suggestion_text,
        )
        db.add(suggestion)
        question.ai_suggestion = suggestion
    db.flush()


def extract_ml_questions(raw_response: Any) -> list[dict[str, Any]]:
    if isinstance(raw_response, list):
        return raw_response
    if not isinstance(raw_response, dict):
        return []
    questions_payload = raw_response.get("questions") or raw_response.get("results") or []
    return questions_payload if isinstance(questions_payload, list) else []


def fetch_ml_questions_by_seller(seller_id: str, access_token: str) -> dict[str, Any]:
    query = urlencode(
        {
            "seller_id": seller_id,
            "status": "unanswered",
            "api_version": "4",
        }
    )
    try:
        return ml_request_json(
            f"{ML_API_BASE_URL}/questions/search?{query}",
            access_token=access_token,
        )
    except HTTPException as error:
        if error.status_code in {400, 404}:
            return ml_request_json(
                f"{ML_API_BASE_URL}/marketplace/questions/search?{query}",
                access_token=access_token,
            )
        raise


def fetch_ml_item_ids_by_seller(seller_id: str, access_token: str) -> list[str]:
    item_ids: list[str] = []
    offset = 0
    limit = 50
    while True:
        query = urlencode({"limit": limit, "offset": offset})
        response = ml_request_json(
            f"{ML_API_BASE_URL}/users/{seller_id}/items/search?{query}",
            access_token=access_token,
        )
        results = response.get("results") if isinstance(response, dict) else []
        if not isinstance(results, list) or not results:
            break
        item_ids.extend(str(item_id) for item_id in results if item_id)
        paging = response.get("paging") or {}
        total = int(paging.get("total") or len(item_ids))
        offset += len(results)
        if offset >= total:
            break
    return item_ids


def product_to_api(product: ProductCache) -> dict[str, Any]:
    return {
        "id": product.id,
        "company_id": product.company_id,
        "provider": product.provider,
        "external_id": product.external_id,
        "title": product.title,
        "permalink": product.permalink,
        "price": product.price,
        "currency_id": product.currency_id,
        "status": product.status,
        "available_quantity": product.available_quantity,
        "thumbnail": product.thumbnail,
        "category_id": product.category_id,
        "listing_type_id": product.listing_type_id,
        "condition": product.condition,
        "seller_custom_field": product.seller_custom_field,
        "attributes_json": product.attributes_json or [],
        "variations_json": product.variations_json or [],
        "raw_payload": product.raw_payload or {},
        "last_synced_at": product.last_synced_at.isoformat() if product.last_synced_at else None,
        "created_at": product.created_at.isoformat() if product.created_at else None,
        "updated_at": product.updated_at.isoformat() if product.updated_at else None,
    }


def related_product_to_ai(product: dict[str, Any]) -> str:
    parts = [
        f"titulo={product.get('title') or ''}",
        f"link={product.get('permalink') or ''}",
        f"preco={product.get('price') or ''} {product.get('currency_id') or ''}".strip(),
        f"status={product.get('status') or ''}",
        f"quantidade_disponivel={product.get('available_quantity')}",
    ]
    attributes = product.get("attributes_json") or []
    if isinstance(attributes, list):
        attribute_summary = []
        for attribute in attributes[:8]:
            if not isinstance(attribute, dict):
                continue
            name = attribute.get("name") or attribute.get("id")
            value = attribute.get("value_name") or attribute.get("value_id")
            if name and value:
                attribute_summary.append(f"{name}: {value}")
        if attribute_summary:
            parts.append(f"atributos={'; '.join(attribute_summary)}")
    return " | ".join(str(part) for part in parts if part)


def build_related_products_context(products: list[dict[str, Any]]) -> str:
    if not products:
        return "Nenhum produto ativo relacionado encontrado no cache."
    return "\n".join(
        f"- {related_product_to_ai(product)}"
        for product in products[:5]
    )


def extract_search_terms(text_value: str) -> list[str]:
    normalized = (
        text_value.lower()
        .replace("/", " ")
        .replace("-", " ")
        .replace("_", " ")
    )
    stopwords = {
        "para", "com", "sem", "uma", "uns", "das", "dos", "que", "tem", "esse", "essa",
        "este", "esta", "produto", "pergunta", "cliente", "serve", "posso", "pode",
        "qual", "como", "quando", "onde", "mais", "menos", "mercado", "livre",
    }
    terms: list[str] = []
    for raw_term in normalized.split():
        term = raw_term.strip(".,;:!?()[]{}\"'")
        if len(term) < 3 or term in stopwords or term.isdigit():
            continue
        if term not in terms:
            terms.append(term)
    return terms[:12]


def score_product_relevance(product: ProductCache, terms: list[str], question_text: str) -> int:
    searchable = " ".join(
        [
            product.title or "",
            product.seller_custom_field or "",
            json.dumps(product.attributes_json or [], ensure_ascii=False),
        ]
    ).lower()
    score = 0
    for term in terms:
        if term in (product.title or "").lower():
            score += 4
        if term in (product.seller_custom_field or "").lower():
            score += 3
        if term in searchable:
            score += 1
    title = (product.title or "").lower()
    if title and title in question_text.lower():
        score += 8
    return score


def search_related_products(question_text: str, limit: int = 5, db: Session | None = None) -> list[dict[str, Any]]:
    owns_session = db is None
    session = db or SessionLocal()
    try:
        try:
            terms = extract_search_terms(question_text)
            if not terms:
                logger.info("Related product search skipped: no useful terms")
                return []
            filters = []
            for term in terms:
                pattern = f"%{term}%"
                filters.append(ProductCache.title.ilike(pattern))
                filters.append(ProductCache.seller_custom_field.ilike(pattern))
                filters.append(cast(ProductCache.attributes_json, Text).ilike(pattern))
            candidates = (
                session.query(ProductCache)
                .filter(
                    ProductCache.company_id == DEFAULT_COMPANY_ID,
                    ProductCache.provider == DEFAULT_PROVIDER,
                    ProductCache.status == "active",
                    or_(*filters),
                )
                .order_by(ProductCache.updated_at.desc())
                .limit(50)
                .all()
            )
            scored = [
                (score_product_relevance(product, terms, question_text), product)
                for product in candidates
            ]
            scored = [(score, product) for score, product in scored if score > 0]
            scored.sort(key=lambda item: item[0], reverse=True)
            products = [product_to_api(product) for _, product in scored[:limit]]
            logger.info("Related products found count=%s terms=%s", len(products), terms[:6])
            return products
        except Exception:
            logger.exception("Related product search failed; continuing without product context")
            return []
    finally:
        if owns_session:
            session.close()


def upsert_ml_product(db: Session, item_payload: dict[str, Any]) -> tuple[ProductCache, bool]:
    external_id = str(item_payload.get("id") or "")
    if not external_id:
        raise ValueError("Mercado Livre product missing id")
    product = (
        db.query(ProductCache)
        .filter(
            ProductCache.company_id == DEFAULT_COMPANY_ID,
            ProductCache.provider == DEFAULT_PROVIDER,
            ProductCache.external_id == external_id,
        )
        .first()
    )
    created = product is None
    if created:
        product = ProductCache(
            company_id=DEFAULT_COMPANY_ID,
            provider=DEFAULT_PROVIDER,
            external_id=external_id,
        )
        db.add(product)
    product.title = item_payload.get("title") or ""
    product.permalink = item_payload.get("permalink") or ""
    product.price = str(item_payload.get("price")) if item_payload.get("price") is not None else None
    product.currency_id = item_payload.get("currency_id")
    product.status = item_payload.get("status")
    product.available_quantity = item_payload.get("available_quantity")
    product.thumbnail = item_payload.get("thumbnail")
    product.category_id = item_payload.get("category_id")
    product.listing_type_id = item_payload.get("listing_type_id")
    product.condition = item_payload.get("condition")
    product.seller_custom_field = item_payload.get("seller_custom_field")
    product.attributes_json = item_payload.get("attributes") or []
    product.variations_json = item_payload.get("variations") or []
    product.raw_payload = item_payload
    product.last_synced_at = datetime.utcnow()
    product.updated_at = datetime.utcnow()
    return product, created


def sync_mercadolivre_products(db: Session) -> dict[str, Any]:
    logger.info("Mercado Livre products sync started")
    access_token = get_valid_mercadolivre_token(db)
    integration = get_ml_integration(db)
    seller_id = integration.seller_id or get_ml_seller_id(
        {"access_token": access_token, "seller_id": integration.seller_id}
    )
    try:
        item_ids = fetch_ml_item_ids_by_seller(str(seller_id), access_token)
    except HTTPException as error:
        if error.status_code != 401:
            raise
        access_token = get_valid_mercadolivre_token(db, force_refresh=True)
        item_ids = fetch_ml_item_ids_by_seller(str(seller_id), access_token)
    logger.info("Mercado Livre product item ids fetched count=%s", len(item_ids))

    stats = {
        "fetched": len(item_ids),
        "created": 0,
        "updated": 0,
        "active": 0,
        "inactive": 0,
    }

    for item_id in item_ids:
        try:
            try:
                item_payload = ml_request_json(f"{ML_API_BASE_URL}/items/{quote(str(item_id), safe='')}", access_token=access_token)
            except HTTPException as error:
                if error.status_code != 401:
                    raise
                access_token = get_valid_mercadolivre_token(db, force_refresh=True)
                item_payload = ml_request_json(f"{ML_API_BASE_URL}/items/{quote(str(item_id), safe='')}", access_token=access_token)
            product, created = upsert_ml_product(db, item_payload)
            stats["created" if created else "updated"] += 1
            if product.status == "active":
                stats["active"] += 1
            else:
                stats["inactive"] += 1
        except Exception as error:
            logger.exception("Mercado Livre product sync item failed item_id=%s error=%s", item_id, error)
            continue

    db.commit()
    logger.info(
        "Mercado Livre products sync finished fetched=%s created=%s updated=%s active=%s inactive=%s",
        stats["fetched"],
        stats["created"],
        stats["updated"],
        stats["active"],
        stats["inactive"],
    )
    return stats


def sync_mercadolivre_questions(db: Session, *, source: str = "manual") -> dict[str, Any]:
    logger.info("Mercado Livre sync started source=%s", source)
    stats = {
        "created": 0,
        "updated": 0,
        "questions_fetched": 0,
        "suggestions_generated": 0,
        "marked_responded": 0,
    }

    def run_with_tokens(force_refresh: bool = False) -> dict[str, Any]:
        access_token = get_valid_mercadolivre_token(db, force_refresh=force_refresh)
        integration = get_ml_integration(db)
        tokens = {
            "access_token": access_token,
            "seller_id": integration.seller_id,
            "user_id": integration.seller_id,
        }
        seller_id = get_ml_seller_id(tokens)
        raw_response = fetch_ml_questions_by_seller(
            seller_id=seller_id,
            access_token=tokens["access_token"],
        )
        logger.info("Mercado Livre questions raw response source=%s body=%s", source, raw_response)
        print(f"Mercado Livre questions raw response source={source}: {raw_response}")

        fetched_external_ids: set[str] = set()
        saved_questions: list[QuestionRecord] = []
        questions_payload = extract_ml_questions(raw_response)
        stats["questions_fetched"] = len(questions_payload)

        for question_payload in questions_payload:
            normalized = normalize_ml_question(question_payload, tokens["access_token"])
            external_id = str(normalized.get("external_id") or "")
            if not external_id:
                logger.warning("Mercado Livre sync ignored question without external_id source=%s payload=%s", source, question_payload)
                continue
            fetched_external_ids.add(external_id)
            existing_question = (
                db.query(QuestionRecord)
                .filter(
                    QuestionRecord.company_id == DEFAULT_COMPANY_ID,
                    QuestionRecord.provider == DEFAULT_PROVIDER,
                    QuestionRecord.external_id == external_id,
                )
                .first()
            )
            had_suggestion = bool(get_suggestion_text(existing_question.ai_suggestion)) if existing_question else False
            question = upsert_ml_question(db, normalized)
            stats["updated" if existing_question else "created"] += 1
            ensure_initial_suggestion(db, question)
            if not had_suggestion and get_suggestion_text(question.ai_suggestion):
                stats["suggestions_generated"] += 1
            saved_questions.append(question)

        local_pending_questions = (
            db.query(QuestionRecord)
            .filter(
                QuestionRecord.company_id == DEFAULT_COMPANY_ID,
                QuestionRecord.provider == DEFAULT_PROVIDER,
                QuestionRecord.status == "pending",
            )
            .all()
        )
        for question in local_pending_questions:
            if question.external_id in fetched_external_ids:
                continue
            try:
                question_detail = fetch_ml_question_detail(question.external_id, tokens["access_token"])
            except HTTPException as error:
                logger.warning(
                    "Could not verify pending ML question during sync source=%s external_id=%s detail=%s",
                    source,
                    question.external_id,
                    error.detail,
                )
                continue
            if not ml_question_is_answered(question_detail):
                continue
            final_answer = extract_ml_answer_text(question_detail) or "Respondida no Mercado Livre."
            updated_question = save_answered_question_state(
                db,
                question_id=question.external_id,
                approved_answer=final_answer,
                payload=MercadoLivreAnswerPayload(answer=final_answer),
                raw_response=question_detail,
            )
            stats["marked_responded"] += 1
            if updated_question:
                saved_questions.append(updated_question)

        integration = get_ml_integration(db)
        integration.last_sync = datetime.utcnow()
        integration.token_status = "valid"
        db.commit()
        logger.info(
            "Mercado Livre sync finished source=%s fetched=%s created=%s updated=%s suggestions=%s marked_responded=%s",
            source,
            stats["questions_fetched"],
            stats["created"],
            stats["updated"],
            stats["suggestions_generated"],
            stats["marked_responded"],
        )
        return {
            "questions": [question_to_api(question, db=db) for question in saved_questions],
            "stats": stats,
        }

    try:
        return run_with_tokens()
    except HTTPException as error:
        if error.status_code != 401:
            logger.exception("Mercado Livre sync failed source=%s", source)
            raise
        logger.info("Mercado Livre sync refreshing token source=%s", source)
        return run_with_tokens(force_refresh=True)


def run_mercadolivre_sync_background(source: str, payload: Any | None = None) -> None:
    db = SessionLocal()
    try:
        logger.info("Mercado Livre background sync started source=%s payload=%s", source, safe_log_payload(payload))
        sync_mercadolivre_questions(db, source=source)
    except Exception:
        logger.exception("Mercado Livre background sync error source=%s", source)
    finally:
        db.close()


def safe_log_payload(payload: Any, *, max_length: int = 2000) -> str:
    try:
        text = json.dumps(payload, ensure_ascii=False, default=str)
    except Exception:
        text = repr(payload)
    if len(text) > max_length:
        return f"{text[:max_length]}... [truncated]"
    return text


class Status(str, Enum):
    pending = "Pendente"
    approved = "Aprovada"
    answered = "Respondida"
    rejected = "Rejeitada"


class Priority(str, Enum):
    high = "Alta"
    medium = "Media"
    low = "Baixa"


class Question(BaseModel):
    id: int
    marketplace: str
    product: str
    customer_name: str
    question: str
    created_at: datetime
    status: Status
    priority: Priority
    ai_suggestion: str
    sku: str
    price: str
    raw_payload: dict[str, Any] = Field(default_factory=dict)


class SuggestionResponse(BaseModel):
    suggestion: str


class ApprovePayload(BaseModel):
    answer: str


class AiSuggestionPayload(BaseModel):
    product_title: str = ""
    question_text: str


class MercadoLivreAnswerPayload(BaseModel):
    answer: str
    original_suggestion: str = ""
    was_edited: bool = False
    instruction_used: str = ""


class CompanySettingsPayload(BaseModel):
    greeting: str = ""
    closing: str = ""
    tone: str = ""
    custom_prompt: str = ""


app = FastAPI(title="Marketplace AI Inbox API", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
def startup_event():
    init_database()


def raise_connector_http_error(error: ConnectorError) -> None:
    status_by_code = {
        ConnectorErrorCode.missing_fields: 502,
        ConnectorErrorCode.token_expired: 401,
        ConnectorErrorCode.rate_limited: 429,
        ConnectorErrorCode.api_failure: 502,
    }
    raise HTTPException(
        status_code=status_by_code.get(error.code, 502),
        detail=serialize_connector_error(error),
    )


questions: List[Question] = [
    Question(
        id=1,
        marketplace="Mercado Livre",
        product="Kit 3 Camisetas Premium Algodao",
        customer_name="Mariana",
        question="Boa tarde! Esse kit tem a camiseta preta no tamanho M? Entrega chega antes de sexta?",
        created_at=datetime(2026, 4, 25, 10, 42),
        status=Status.pending,
        priority=Priority.high,
        ai_suggestion="Ola, Mariana! Temos sim a camiseta preta no tamanho M. Para confirmar o prazo de chegada antes de sexta, basta inserir seu CEP no anuncio que o Mercado Livre mostra a estimativa atualizada. Ficamos a disposicao!",
        sku="CAM-KIT-003",
        price="R$ 129,90",
    ),
    Question(
        id=2,
        marketplace="Mercado Livre",
        product="Fone Bluetooth Noise Canceling Pro",
        customer_name="Diego",
        question="O produto e original? Tem garantia?",
        created_at=datetime(2026, 4, 25, 9, 18),
        status=Status.pending,
        priority=Priority.medium,
        ai_suggestion="Ola, Diego! Sim, o produto e original, acompanha nota fiscal e possui garantia de 12 meses contra defeitos de fabricacao. Pode comprar com tranquilidade.",
        sku="FON-BT-PRO",
        price="R$ 249,00",
    ),
    Question(
        id=3,
        marketplace="Mercado Livre",
        product="Suporte Articulado para Monitor",
        customer_name="Carla",
        question="Serve para monitor ultrawide de 34 polegadas?",
        created_at=datetime(2026, 4, 24, 17, 5),
        status=Status.approved,
        priority=Priority.low,
        ai_suggestion="Ola, Carla! Esse suporte e compativel com monitores de ate 32 polegadas. Para ultrawide de 34 polegadas, recomendamos verificar peso e padrao VESA antes da compra.",
        sku="SUP-MON-ARM",
        price="R$ 189,90",
    ),
    Question(
        id=4,
        marketplace="Mercado Livre",
        product="Mochila Executiva Impermeavel USB",
        customer_name="Renato",
        question="Cabe notebook de 15.6 e tem divisoria acolchoada?",
        created_at=datetime(2026, 4, 24, 14, 32),
        status=Status.answered,
        priority=Priority.medium,
        ai_suggestion="Ola, Renato! Cabe notebook de ate 15.6 polegadas e possui divisoria acolchoada para melhor protecao. Tambem conta com tecido resistente a respingos.",
        sku="MOC-EXEC-USB",
        price="R$ 159,90",
    ),
    Question(
        id=5,
        marketplace="Shopee",
        product="Organizador de Cabos Mesa Home Office",
        customer_name="Luciana",
        question="Vem com fita dupla face para instalar?",
        created_at=datetime(2026, 4, 23, 11, 20),
        status=Status.pending,
        priority=Priority.low,
        ai_suggestion="Ola, Luciana! Sim, o organizador acompanha fita dupla face para uma instalacao pratica na mesa. Recomendamos limpar a superficie antes de colar.",
        sku="ORG-CAB-HO",
        price="R$ 39,90",
    ),
    Question(
        id=6,
        marketplace="Shopee",
        product="Luminaria LED Articulada para Mesa",
        customer_name="Paulo",
        question="A luz tem ajuste de intensidade? Funciona ligada no USB do notebook?",
        created_at=datetime(2026, 4, 26, 16, 10),
        status=Status.approved,
        priority=Priority.medium,
        ai_suggestion="Ola, Paulo! Sim, a luminaria possui ajuste de intensidade e funciona via USB, inclusive conectada ao notebook. Recomendamos usar uma porta com boa alimentacao para melhor desempenho.",
        sku="LUM-LED-USB",
        price="R$ 74,90",
    ),
    Question(
        id=7,
        marketplace="Magalu",
        product="Cafeteira Espresso Compacta 20 Bar",
        customer_name="Bianca",
        question="Ela aceita capsula ou somente po de cafe?",
        created_at=datetime(2026, 4, 26, 13, 48),
        status=Status.pending,
        priority=Priority.high,
        ai_suggestion="Ola, Bianca! Esse modelo utiliza po de cafe e acompanha filtro proprio. Ele nao e compativel com capsulas. Ficamos a disposicao para ajudar na compra!",
        sku="CAF-ESP-20B",
        price="R$ 599,00",
    ),
    Question(
        id=8,
        marketplace="Amazon",
        product="Echo Speaker Smart Home Hub",
        customer_name="Andre",
        question="Consigo controlar lampadas inteligentes de outras marcas?",
        created_at=datetime(2026, 4, 26, 8, 25),
        status=Status.answered,
        priority=Priority.low,
        ai_suggestion="Ola, Andre! Sim, voce consegue controlar lampadas inteligentes compativeis com Alexa. Recomendamos verificar na embalagem ou no app do fabricante se ha suporte para Alexa.",
        sku="ECH-HUB-5G",
        price="R$ 429,00",
    ),
    Question(
        id=9,
        marketplace="Magalu",
        product="Aspirador Robo Smart Mapeamento",
        customer_name="Fernanda",
        question="Ele passa pano tambem ou so aspira?",
        created_at=datetime(2026, 4, 25, 19, 4),
        status=Status.pending,
        priority=Priority.medium,
        ai_suggestion="Ola, Fernanda! Esse modelo aspira e tambem passa pano com reservatorio de agua. Para melhor resultado, recomendamos usar em pisos frios ou laminados bem nivelados.",
        sku="ASP-ROB-MAP",
        price="R$ 899,90",
    ),
    Question(
        id=10,
        marketplace="Amazon",
        product="Kindle Paperwhite 16 GB",
        customer_name="Roberto",
        question="O aparelho vem com anuncios na tela de bloqueio?",
        created_at=datetime(2026, 4, 25, 15, 36),
        status=Status.approved,
        priority=Priority.low,
        ai_suggestion="Ola, Roberto! Este anuncio e da versao sem ofertas especiais, portanto nao exibe anuncios na tela de bloqueio. O produto e novo e acompanha cabo USB.",
        sku="KDL-PW-16",
        price="R$ 699,00",
    ),
]


suggestion_variants = [
    "Obrigado pela pergunta! Conferimos as informacoes do produto e podemos te atender com seguranca. ",
    "Ola! Sim, esse item esta pronto para envio e as condicoes atualizadas aparecem no proprio marketplace. ",
    "Oi! Para garantir a melhor compra, recomendamos validar o prazo pelo CEP no anuncio. Sobre o produto: ",
]


def find_question(question_id: int) -> Question:
    for question in questions:
        if question.id == question_id:
            return question
    raise HTTPException(status_code=404, detail="Pergunta nao encontrada")


@app.get("/health")
def health():
    return {"status": "ok"}


def generate_openai_rewrite(
    question: str,
    original_response: str,
    instruction: str,
    settings: CompanySettings | None = None,
    related_products: list[dict[str, Any]] | None = None,
) -> str:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not configured")

    from openai import OpenAI

    client = OpenAI(api_key=api_key)
    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    greeting = settings.greeting if settings else "Olá! Obrigado pela pergunta."
    closing = settings.closing if settings else "Ficamos à disposição."
    tone = settings.tone if settings else "Técnico, claro e confiável"
    custom_prompt = settings.custom_prompt if settings else ""
    related_products_context = build_related_products_context(related_products or [])

    prompt = (
        "Você é um vendedor profissional de e-commerce respondendo perguntas no Mercado Livre. "
        "Reescreva a resposta conforme a instrução do usuário.\n\n"
        "Rules:\n"
        "- Responda em português do Brasil.\n"
        f"- Tom desejado: {tone}.\n"
        f"- Use a saudação padrão quando fizer sentido: {greeting}\n"
        f"- Use a despedida padrão quando fizer sentido: {closing}\n"
        "- Seja educado, direto, útil e levemente persuasivo.\n"
        "- Comece com uma resposta curta e depois adicione detalhe útil.\n"
        "- Não invente detalhes de produto, estoque, prazo, garantia, compatibilidade ou características.\n"
        "- Se a informação for incerta, responda com cautela e oriente o cliente a conferir a variação do anúncio ou enviar nova mensagem.\n"
        "- NUNCA invente links, produtos, estoque ou compatibilidades.\n"
        "- Use SOMENTE produtos ativos listados no contexto de produtos relacionados.\n"
        "- Se sugerir produto complementar, inclua apenas link real do cache e somente quando a relevância for clara.\n"
        "- Nunca prometa estoque indisponível.\n"
        "- Evite frases genéricas como 'recomendamos verificar'.\n"
        "- Máximo de 5 linhas, salvo se a instrução pedir outra coisa.\n"
        "- Retorne apenas a resposta final pronta para envio. Sem explicação, sem meta texto.\n\n"
        f"Prompt personalizado da empresa: {custom_prompt or 'Nenhum'}\n\n"
        f"Produtos ativos relacionados encontrados no cache:\n{related_products_context}\n\n"
        f"Pergunta do cliente:\n{question}\n\n"
        f"Resposta atual do vendedor:\n{original_response}\n\n"
        f"Instrução de reescrita:\n{instruction}"
    )
    response = client.responses.create(model=model, input=prompt)
    revised_response = response.output_text.strip()
    if not revised_response:
        raise RuntimeError("OpenAI returned an empty response")
    return revised_response


def generate_openai_initial_suggestion(
    product_title: str,
    question_text: str,
    settings: CompanySettings | None = None,
    related_products: list[dict[str, Any]] | None = None,
) -> str:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not configured")

    from openai import OpenAI

    client = OpenAI(api_key=api_key)
    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    greeting = settings.greeting if settings else "Olá!"
    closing = settings.closing if settings else "Ficamos à disposição."
    tone = settings.tone if settings else "Técnico, claro e confiável"
    custom_prompt = settings.custom_prompt if settings else ""
    related_products_context = build_related_products_context(related_products or [])
    prompt = (
        "Você é um vendedor profissional de e-commerce respondendo perguntas no Mercado Livre.\n"
        "Crie uma resposta inicial pronta para envio.\n\n"
        "Regras:\n"
        "- Responda em português do Brasil.\n"
        f"- Tom desejado: {tone}.\n"
        f"- Se fizer sentido, use esta saudação curta: {greeting}\n"
        f"- Se fizer sentido, encerre com: {closing}\n"
        "- Comece com a resposta curta e depois detalhe somente o necessário.\n"
        "- Não invente informações sobre estoque, prazo, garantia, compatibilidade ou características.\n"
        "- NUNCA invente links ou produtos.\n"
        "- Use SOMENTE produtos ativos listados no contexto de produtos relacionados.\n"
        "- Se houver produto complementar claramente relevante, sugira de forma natural com o link real do Mercado Livre.\n"
        "- Exemplos: pergunta sobre CPAP pode mencionar máscaras compatíveis se encontradas; pergunta sobre máscara pode mencionar CPAP compatível; pergunta sobre umidificador pode mencionar tubo/filtro disponível.\n"
        "- Não force recomendação se a relevância for baixa.\n"
        "- Nunca prometa estoque indisponível.\n"
        "- Se os dados forem insuficientes, diga que o cliente pode conferir a variação do anúncio ou enviar nova mensagem.\n"
        "- Não mencione IA, sistema, API ou instruções internas.\n"
        "- Máximo de 5 linhas.\n\n"
        f"Prompt personalizado da empresa: {custom_prompt or 'Nenhum'}\n\n"
        f"Produtos ativos relacionados encontrados no cache:\n{related_products_context}\n\n"
        f"Produto: {product_title or 'Produto não informado'}\n"
        f"Pergunta do cliente: {question_text}"
    )
    response = client.responses.create(model=model, input=prompt)
    suggestion = response.output_text.strip()
    if not suggestion:
        raise RuntimeError("OpenAI returned an empty response")
    return suggestion


@app.get("/ai/health")
def ai_health():
    return {
        "openai_key_configured": bool(os.getenv("OPENAI_API_KEY")),
        "model": os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
        "status": "ok",
    }


@app.post("/ai/suggest")
def suggest_ai_response(payload: AiSuggestionPayload, db: Session = Depends(get_db)):
    question_text = payload.question_text.strip()
    if not question_text:
        raise HTTPException(status_code=400, detail="Missing required field: question_text")

    try:
        suggestion = generate_openai_initial_suggestion(
            product_title=payload.product_title.strip(),
            question_text=question_text,
            settings=get_default_settings(db),
            related_products=search_related_products(
                f"{payload.product_title} {question_text}",
                limit=5,
                db=db,
            ),
        )
        logger.info("AI initial suggestion generated from /ai/suggest")
        return {"suggestion": suggestion}
    except Exception as error:
        logger.exception("OpenAI initial suggestion failed")
        print(f"OpenAI initial suggestion failed: {error}")
        return {
            "error": True,
            "message": f"OpenAI initial suggestion failed: {error}",
            "fallback_available": False,
        }


@app.get("/integrations/mercadolivre/auth-url")
def mercadolivre_auth_url():
    config = get_ml_config()
    if not ml_is_configured():
        return {
            "configured": False,
            "auth_url": None,
            "fallback_available": True,
            "message": "Mercado Livre OAuth is not configured. Set ML_CLIENT_ID, ML_CLIENT_SECRET and ML_REDIRECT_URI.",
        }

    query = urlencode(
        {
            "response_type": "code",
            "client_id": config["client_id"],
            "redirect_uri": config["redirect_uri"],
            "state": "marketplace-ai-inbox",
        }
    )
    return {"configured": True, "auth_url": f"{ML_AUTH_BASE_URL}?{query}"}


@app.get("/integrations/mercadolivre/callback")
def mercadolivre_callback(code: str = Query(...)):
    config = get_ml_config()
    if not ml_is_configured():
        raise HTTPException(status_code=400, detail="Mercado Livre OAuth is not configured")

    token_data = ml_request_json(
        f"{ML_API_BASE_URL}/oauth/token",
        method="POST",
        data={
            "grant_type": "authorization_code",
            "client_id": config["client_id"],
            "client_secret": config["client_secret"],
            "code": code,
            "redirect_uri": config["redirect_uri"],
        },
    )
    tokens = save_ml_tokens(token_data)
    try:
        seller_id = get_ml_seller_id(tokens)
        tokens = update_ml_tokens({"seller_id": seller_id})
    except HTTPException as error:
        logger.warning("Could not resolve Mercado Livre seller_id after OAuth: %s", error.detail)
    frontend_url = os.getenv("FRONTEND_URL")
    if frontend_url:
        return RedirectResponse(f"{frontend_url.rstrip('/')}/?ml_connected=true")
    return {
        "connected": True,
        "message": "Mercado Livre connected. You can close this tab and return to the app.",
    }


@app.get("/integrations/mercadolivre/questions")
def mercadolivre_questions(db: Session = Depends(get_db)):
    try:
        result = sync_mercadolivre_questions(db, source="manual")
        return result["questions"]
    except HTTPException as error:
        if error.status_code == 403:
            raise HTTPException(
                status_code=403,
                detail="Permissão insuficiente para acessar perguntas.",
            ) from error
        raise


@app.post("/integrations/mercadolivre/notifications")
def mercadolivre_notifications(
    background_tasks: BackgroundTasks,
    payload: Any = Body(default=None),
):
    try:
        logger.info("Mercado Livre notification received payload=%s", safe_log_payload(payload))
        print(f"Mercado Livre notification received payload={safe_log_payload(payload)}")
        background_tasks.add_task(run_mercadolivre_sync_background, "webhook", payload)
    except Exception:
        logger.exception("Mercado Livre notification handler failed before scheduling background sync")
    return {"ok": True}


@app.post("/jobs/sync-mercadolivre")
def sync_mercadolivre_job(db: Session = Depends(get_db)):
    result = sync_mercadolivre_questions(db, source="job")
    return {"ok": True, "stats": result["stats"]}


@app.post("/integrations/mercadolivre/products/sync")
def sync_mercadolivre_products_endpoint(db: Session = Depends(get_db)):
    return sync_mercadolivre_products(db)


def send_ml_answer(question_id: str, answer: str, access_token: str) -> dict[str, Any]:
    question_identifier: int | str = int(question_id) if str(question_id).isdigit() else question_id
    response_status, response_body = ml_request_json_with_status(
        f"{ML_API_BASE_URL}/answers",
        method="POST",
        json_data={
            "question_id": question_identifier,
            "text": answer,
        },
        access_token=access_token,
    )
    logger.info("Mercado Livre answer response status=%s body=%s", response_status, response_body)
    print(f"Mercado Livre answer response status={response_status} body={response_body}")
    return {"status": response_status, "body": response_body}


def fetch_ml_question_detail(question_id: str, access_token: str) -> dict[str, Any]:
    encoded_question_id = quote(str(question_id), safe="")
    try:
        return ml_request_json(
            f"{ML_API_BASE_URL}/questions/{encoded_question_id}?api_version=4",
            access_token=access_token,
        )
    except HTTPException as error:
        if error.status_code in {400, 404}:
            return ml_request_json(
                f"{ML_API_BASE_URL}/marketplace/questions/{encoded_question_id}",
                access_token=access_token,
            )
        raise


def extract_ml_answer_text(question_payload: dict[str, Any] | None) -> str:
    if not isinstance(question_payload, dict):
        return ""
    answer = question_payload.get("answer") or {}
    if not isinstance(answer, dict):
        return ""
    return answer.get("text") or answer.get("text_translated") or ""


def ml_question_is_answered(question_payload: dict[str, Any] | None) -> bool:
    if not isinstance(question_payload, dict):
        return False
    status = normalize_db_status(question_payload.get("status"))
    return status == "responded" or bool(extract_ml_answer_text(question_payload))


def is_already_answered_error(error: HTTPException) -> bool:
    detail = str(error.detail or "").lower()
    return (
        "already answered" in detail
        or "question already answered" in detail
        or "já foi respondida" in detail
        or "ja foi respondida" in detail
        or "pergunta respondida" in detail
    )


def save_answered_question_state(
    db: Session,
    *,
    question_id: str,
    approved_answer: str,
    payload: MercadoLivreAnswerPayload,
    raw_response: dict[str, Any] | None = None,
) -> QuestionRecord | None:
    now = datetime.utcnow()
    question = (
        db.query(QuestionRecord)
        .filter(
            QuestionRecord.company_id == DEFAULT_COMPANY_ID,
            QuestionRecord.provider == DEFAULT_PROVIDER,
            QuestionRecord.external_id == str(question_id),
        )
        .first()
    )
    final_answer = extract_ml_answer_text(raw_response) or approved_answer
    if question:
        question.status = "responded"
        question.answered_at = now
        question.updated_at = now
        if raw_response:
            question.raw_payload = raw_response
        if question.ai_suggestion:
            suggestion = question.ai_suggestion
            if payload.original_suggestion:
                suggestion.original_suggestion = payload.original_suggestion
                suggestion.suggestion_text = suggestion.suggestion_text or payload.original_suggestion
            if payload.was_edited and final_answer == approved_answer:
                suggestion.edited_text = approved_answer
            suggestion.final_response = final_answer
            suggestion.final_answer = final_answer
            suggestion.was_edited = payload.was_edited
            suggestion.instruction_used = payload.instruction_used
            suggestion.approved_by = "Admin"
            suggestion.approved_at = now
            suggestion.updated_at = now
        else:
            db.add(
                AiSuggestion(
                    question=question,
                    original_suggestion=payload.original_suggestion or final_answer,
                    suggestion_text=payload.original_suggestion or final_answer,
                    edited_text=approved_answer if payload.was_edited and final_answer == approved_answer else None,
                    final_response=final_answer,
                    final_answer=final_answer,
                    was_edited=payload.was_edited,
                    instruction_used=payload.instruction_used,
                    approved_by="Admin",
                    approved_at=now,
                )
            )
        db.commit()
        db.refresh(question)
    return question


@app.post("/integrations/mercadolivre/questions/{question_id}/answer")
def answer_mercadolivre_question(
    question_id: str,
    payload: MercadoLivreAnswerPayload,
    db: Session = Depends(get_db),
):
    answer = payload.answer.strip()
    if not answer:
        raise HTTPException(status_code=400, detail="Missing required field: answer")

    try:
        access_token = get_valid_mercadolivre_token(db)
        try:
            question_detail = fetch_ml_question_detail(question_id, access_token)
            if ml_question_is_answered(question_detail):
                question = save_answered_question_state(
                    db,
                    question_id=question_id,
                    approved_answer=answer,
                    payload=payload,
                    raw_response=question_detail,
                )
                return {
                    "sent": False,
                    "already_answered": True,
                    "message": "Essa pergunta já foi respondida no Mercado Livre.",
                    "raw_response": question_detail,
                    "question": question_to_api(question, db=db) if question else None,
                }
        except HTTPException as status_error:
            if status_error.status_code in {401, 403}:
                raise
            logger.warning("Could not verify Mercado Livre question status before answering: %s", status_error.detail)
        result = send_ml_answer(question_id, answer, access_token)
    except HTTPException as error:
        if error.status_code == 401:
            access_token = get_valid_mercadolivre_token(db, force_refresh=True)
            try:
                question_detail = fetch_ml_question_detail(question_id, access_token)
                if ml_question_is_answered(question_detail):
                    question = save_answered_question_state(
                        db,
                        question_id=question_id,
                        approved_answer=answer,
                        payload=payload,
                        raw_response=question_detail,
                    )
                    return {
                        "sent": False,
                        "already_answered": True,
                        "message": "Essa pergunta já foi respondida no Mercado Livre.",
                        "raw_response": question_detail,
                        "question": question_to_api(question, db=db) if question else None,
                    }
            except HTTPException as status_error:
                if status_error.status_code == 403:
                    raise
                logger.warning("Could not verify Mercado Livre question status after refresh: %s", status_error.detail)
            try:
                result = send_ml_answer(question_id, answer, access_token)
            except HTTPException as send_error:
                if not is_already_answered_error(send_error):
                    raise
                try:
                    question_detail = fetch_ml_question_detail(question_id, access_token)
                except HTTPException:
                    question_detail = {}
                question = save_answered_question_state(
                    db,
                    question_id=question_id,
                    approved_answer=answer,
                    payload=payload,
                    raw_response=question_detail,
                )
                return {
                    "sent": False,
                    "already_answered": True,
                    "message": "Essa pergunta já foi respondida no Mercado Livre.",
                    "raw_response": question_detail,
                    "question": question_to_api(question, db=db) if question else None,
                }
        elif error.status_code == 403:
            raise HTTPException(
                status_code=403,
                detail="Permissão insuficiente para enviar respostas ao Mercado Livre.",
            ) from error
        elif is_already_answered_error(error):
            try:
                access_token = get_valid_mercadolivre_token(db)
                question_detail = fetch_ml_question_detail(question_id, access_token)
            except HTTPException:
                question_detail = {}
            question = save_answered_question_state(
                db,
                question_id=question_id,
                approved_answer=answer,
                payload=payload,
                raw_response=question_detail,
            )
            return {
                "sent": False,
                "already_answered": True,
                "message": "Essa pergunta já foi respondida no Mercado Livre.",
                "raw_response": question_detail,
                "question": question_to_api(question, db=db) if question else None,
            }
        else:
            raise

    question = save_answered_question_state(
        db,
        question_id=question_id,
        approved_answer=answer,
        payload=payload,
        raw_response=result["body"],
    )

    return {
        "sent": True,
        "already_answered": False,
        "message": "Resposta enviada ao Mercado Livre",
        "raw_response": result["body"],
        "question": question_to_api(question, db=db) if question else None,
    }


@app.post("/ai/rewrite")
def rewrite_ai_response(payload: dict[str, Any], db: Session = Depends(get_db)):
    original_response = (payload.get("text") or payload.get("original_response") or "").strip()
    instruction = (payload.get("instruction") or "").strip()
    question = (payload.get("question") or "").strip()

    if not original_response:
        return {
            "error": True,
            "message": "Missing required field: text or original_response",
            "fallback_available": True,
        }

    if not instruction:
        raise HTTPException(status_code=400, detail="Missing required field: instruction")

    try:
        related_products = search_related_products(question, limit=5, db=db)
        logger.info("Injecting related products into AI rewrite count=%s", len(related_products))
        rewritten_text = generate_openai_rewrite(
            question,
            original_response,
            instruction,
            settings=get_default_settings(db),
            related_products=related_products,
        )
        logger.info("AI rewrite generated successfully")
        return {"rewritten_text": rewritten_text, "related_products": related_products}
    except Exception as error:
        logger.exception("OpenAI rewrite failed")
        print(f"OpenAI rewrite failed: {error}")
        return {
            "error": True,
            "message": f"OpenAI rewrite failed: {error}",
            "fallback_available": True,
        }


@app.get("/integrations/health", response_model=List[IntegrationHealth])
def list_integrations_health(db: Session = Depends(get_db)):
    health_items = []
    for service in integration_services.values():
        try:
            if service.client.id == "mercado-livre":
                integration = get_ml_integration(db)
                connected = False
                token_status = integration.token_status or "missing"
                last_error = "Mercado Livre não conectado."
                if integration.access_token or integration.refresh_token:
                    try:
                        get_valid_mercadolivre_token(db)
                        db.refresh(integration)
                        connected = True
                        token_status = "valid"
                        last_error = None
                    except HTTPException as error:
                        db.refresh(integration)
                        token_status = integration.token_status or "expired"
                        last_error = "Mercado Livre token expirado. Reconecte a integração."
                        logger.warning("Mercado Livre health token refresh failed: %s", error.detail)
                health_items.append(
                    IntegrationHealth(
                        id=service.client.id,
                        channel=service.client.channel,
                        connected=connected,
                        api_status="operational" if connected else "down",
                        last_sync=format_optional_datetime(integration.last_sync),
                        last_error=last_error,
                        token_status=token_status,
                    )
                )
                continue
            health = service.get_health()
            health_items.append(
                IntegrationHealth(
                    id=health.id,
                    channel=health.channel,
                    connected=health.token_status in {"valid", "not_required"},
                    api_status=health.api_status,
                    last_sync=format_optional_datetime(health.last_sync)
                    if isinstance(health.last_sync, datetime)
                    else health.last_sync,
                    last_error=health.last_error,
                    token_status=health.token_status,
                )
            )
        except ConnectorError as error:
            health_items.append(
                IntegrationHealth(
                    id=service.client.id,
                    channel=service.client.channel,
                    connected=False,
                    api_status="down",
                    last_sync=None,
                    last_error=error.message,
                    token_status="missing",
                )
            )
    return health_items


@app.get("/company/settings")
def read_company_settings(db: Session = Depends(get_db)):
    settings = get_default_settings(db)
    return settings_to_api(settings)


def settings_to_api(settings: CompanySettings) -> dict[str, Any]:
    return {
        "id": settings.id,
        "company_id": settings.company_id,
        "greeting": settings.greeting or "Olá! Obrigado pela pergunta.",
        "closing": settings.closing or "Ficamos à disposição.",
        "tone": settings.tone or "Técnico, claro e confiável",
        "custom_prompt": settings.custom_prompt or "",
        "created_at": settings.created_at.isoformat() if settings.created_at else None,
        "updated_at": settings.updated_at.isoformat() if settings.updated_at else None,
    }


def save_company_settings(payload: CompanySettingsPayload, db: Session) -> dict[str, Any]:
    settings = get_default_settings(db)
    settings.greeting = payload.greeting.strip() or "Olá! Obrigado pela pergunta."
    settings.closing = payload.closing.strip() or "Ficamos à disposição."
    settings.tone = payload.tone.strip() or "Técnico, claro e confiável"
    settings.custom_prompt = payload.custom_prompt.strip()
    settings.updated_at = datetime.utcnow()
    db.commit()
    db.refresh(settings)
    return settings_to_api(settings)


@app.put("/company/settings")
def update_company_settings(payload: CompanySettingsPayload, db: Session = Depends(get_db)):
    return save_company_settings(payload, db)


@app.post("/company/settings")
def post_company_settings(payload: CompanySettingsPayload, db: Session = Depends(get_db)):
    return save_company_settings(payload, db)


@app.post("/integrations/{integration_id}/test", response_model=ConnectionTestResult)
def test_integration_connection(integration_id: str):
    service = integration_services.get(integration_id)
    if not service:
        raise HTTPException(status_code=404, detail="Integracao nao encontrada")

    try:
        return service.test_connection()
    except ConnectorError as error:
        raise_connector_http_error(error)
    except Exception as error:
        raise_connector_http_error(ApiFailureError("Unexpected connector failure.", details={"error": str(error)}))


@app.get("/integrations/{integration_id}/questions", response_model=List[NormalizedQuestion])
def list_integration_questions(integration_id: str):
    service = integration_services.get(integration_id)
    if not service:
        raise HTTPException(status_code=404, detail="Integracao nao encontrada")

    try:
        return service.list_questions()
    except ConnectorError as error:
        raise_connector_http_error(error)
    except Exception as error:
        raise_connector_http_error(ApiFailureError("Unexpected connector failure.", details={"error": str(error)}))


@app.get("/questions")
def list_questions(status: str | None = None, db: Session = Depends(get_db)):
    query = (
        db.query(QuestionRecord)
        .filter(QuestionRecord.company_id == DEFAULT_COMPANY_ID)
        .order_by(QuestionRecord.created_at.desc(), QuestionRecord.created_in_app_at.desc())
    )
    if status:
        query = query.filter(QuestionRecord.status == normalize_db_status(status))
    return [question_to_api(question, db=db) for question in query.all()]


@app.get("/products")
def list_products(
    status: str | None = None,
    q: str | None = None,
    db: Session = Depends(get_db),
):
    query = (
        db.query(ProductCache)
        .filter(
            ProductCache.company_id == DEFAULT_COMPANY_ID,
            ProductCache.provider == DEFAULT_PROVIDER,
        )
        .order_by(ProductCache.updated_at.desc(), ProductCache.created_at.desc())
    )
    if status:
        query = query.filter(ProductCache.status == status)
    if q:
        query = query.filter(ProductCache.title.ilike(f"%{q.strip()}%"))
    return [product_to_api(product) for product in query.all()]


@app.post("/questions/generate")
def generate_question_suggestion(payload: dict[str, Any], db: Session = Depends(get_db)):
    question_id = payload.get("question_id") or payload.get("id")
    external_id = payload.get("external_id")
    force = bool(payload.get("force"))
    question = None
    if question_id:
        question = db.get(QuestionRecord, int(question_id))
    if not question and external_id:
        question = (
            db.query(QuestionRecord)
            .filter(
                QuestionRecord.company_id == DEFAULT_COMPANY_ID,
                QuestionRecord.provider == DEFAULT_PROVIDER,
                QuestionRecord.external_id == str(external_id),
            )
            .first()
        )
    if not question:
        raise HTTPException(status_code=404, detail="Pergunta não encontrada")

    if not force and question.ai_suggestion and get_suggestion_text(question.ai_suggestion):
        return question_to_api(question, db=db)

    if force:
        try:
          suggestion_text = generate_openai_initial_suggestion(
              product_title=question.product_title,
              question_text=question.question_text,
              settings=get_default_settings(db),
              related_products=search_related_products(
                  f"{question.product_title or ''} {question.question_text or ''}",
                  limit=5,
                  db=db,
              ),
          )
        except Exception:
            logger.exception("Failed to regenerate AI suggestion for question %s", question.id)
            suggestion_text = (
                "Não foi possível gerar a sugestão da IA agora. "
                "Revise a pergunta e escreva uma resposta antes de enviar."
            )
        now = datetime.utcnow()
        if question.ai_suggestion:
            question.ai_suggestion.original_suggestion = suggestion_text
            question.ai_suggestion.suggestion_text = suggestion_text
            question.ai_suggestion.final_response = suggestion_text
            question.ai_suggestion.final_answer = suggestion_text
            question.ai_suggestion.edited_text = None
            question.ai_suggestion.was_edited = False
            question.ai_suggestion.instruction_used = ""
            question.ai_suggestion.updated_at = now
        else:
            db.add(
                AiSuggestion(
                    question=question,
                    original_suggestion=suggestion_text,
                    suggestion_text=suggestion_text,
                    final_response=suggestion_text,
                    final_answer=suggestion_text,
                )
            )
        question.updated_at = now
    else:
        ensure_initial_suggestion(db, question)
    db.commit()
    db.refresh(question)
    return question_to_api(question, db=db)


@app.post("/questions/answer")
def answer_question(payload: dict[str, Any], db: Session = Depends(get_db)):
    question_id = payload.get("question_id") or payload.get("id")
    external_id = payload.get("external_id")
    answer = (payload.get("answer") or payload.get("final_answer") or payload.get("final_response") or "").strip()
    if not answer:
        raise HTTPException(status_code=400, detail="Missing required field: answer")

    question = None
    if question_id:
        question = db.get(QuestionRecord, int(question_id))
    if not question and external_id:
        question = (
            db.query(QuestionRecord)
            .filter(
                QuestionRecord.company_id == DEFAULT_COMPANY_ID,
                QuestionRecord.provider == DEFAULT_PROVIDER,
                QuestionRecord.external_id == str(external_id),
            )
            .first()
        )
    if not question:
        raise HTTPException(status_code=404, detail="Pergunta não encontrada")

    result = answer_mercadolivre_question(
        question.external_id,
        MercadoLivreAnswerPayload(
            answer=answer,
            original_suggestion=payload.get("suggestion_text") or payload.get("original_suggestion") or "",
            was_edited=bool(payload.get("was_edited")),
            instruction_used=payload.get("instruction_used") or "",
        ),
        db,
    )
    return result


@app.get("/questions/{question_id}")
def get_question(question_id: int, db: Session = Depends(get_db)):
    question = db.get(QuestionRecord, question_id)
    if not question or question.company_id != DEFAULT_COMPANY_ID:
        raise HTTPException(status_code=404, detail="Pergunta não encontrada")
    return question_to_api(question, db=db)


@app.post("/questions/{question_id}/suggest", response_model=SuggestionResponse)
def suggest_answer(question_id: int, db: Session = Depends(get_db)):
    question = db.get(QuestionRecord, question_id)
    if not question:
        question_mock = find_question(question_id)
        variant = suggestion_variants[question_id % len(suggestion_variants)]
        question_mock.ai_suggestion = f"{variant}{question_mock.ai_suggestion}"
        return SuggestionResponse(suggestion=question_mock.ai_suggestion)
    try:
        suggestion_text = generate_openai_initial_suggestion(
            product_title=question.product_title,
            question_text=question.question_text,
            settings=get_default_settings(db),
            related_products=search_related_products(
                f"{question.product_title or ''} {question.question_text or ''}",
                limit=5,
                db=db,
            ),
        )
    except Exception:
        logger.exception("Failed to generate AI suggestion on demand for question %s", question.id)
        suggestion_text = (
            "Não foi possível gerar a sugestão da IA agora. "
            "Revise a pergunta e escreva uma resposta antes de enviar."
        )
    if question.ai_suggestion:
        question.ai_suggestion.original_suggestion = suggestion_text
        question.ai_suggestion.suggestion_text = suggestion_text
        question.ai_suggestion.final_response = suggestion_text
        question.ai_suggestion.final_answer = suggestion_text
        question.ai_suggestion.updated_at = datetime.utcnow()
    else:
        db.add(
            AiSuggestion(
                question=question,
                original_suggestion=suggestion_text,
                suggestion_text=suggestion_text,
                final_response=suggestion_text,
                final_answer=suggestion_text,
            )
        )
    db.commit()
    return SuggestionResponse(suggestion=suggestion_text)


@app.post("/questions/{question_id}/approve")
def approve_question(question_id: int, payload: ApprovePayload, db: Session = Depends(get_db)):
    question = db.get(QuestionRecord, question_id)
    if not question:
        question_mock = find_question(question_id)
        question_mock.ai_suggestion = payload.answer
        question_mock.status = Status.answered
        return question_mock
    now = datetime.utcnow()
    question.status = "responded"
    question.answered_at = now
    if question.ai_suggestion:
        suggestion = question.ai_suggestion
        suggestion.edited_text = payload.answer if payload.answer != get_suggestion_text(suggestion) else suggestion.edited_text
        suggestion.final_response = payload.answer
        suggestion.final_answer = payload.answer
        suggestion.approved_by = "Admin"
        suggestion.approved_at = now
        suggestion.updated_at = now
    else:
        db.add(
            AiSuggestion(
                question=question,
                original_suggestion=payload.answer,
                suggestion_text=payload.answer,
                final_response=payload.answer,
                final_answer=payload.answer,
                approved_by="Admin",
                approved_at=now,
            )
        )
    db.commit()
    db.refresh(question)
    return question_to_api(question, db=db)



